import Head from 'next/head'
import { Inter } from '@next/font/google'
import { useRouter } from 'next/router'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const routes = useRouter()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div className='p-card p-2 m-8 text-center' onClick={() => routes.push("/enterPlayersName")}>
            <h2>Jeu</h2>
        </div>
        <div className='p-card p-2 m-8 text-center'>
          <h2>Score</h2>
        </div>
      </main>
    </>
  )
}
